name: React Native CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-android:
    name: Test on Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: yarn install

      - name: Install Android SDK
        run: sudo apt-get update && sudo apt-get install -y openjdk-11-jdk && sdkmanager --install "platforms;android-31" "build-tools;31.0.0" "platform-tools"

      - name: Run Android Tests
        run: yarn test

  test-ios:
    name: Test on iOS
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: yarn install

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install iOS Dependencies
        run: cd ios && pod install

      - name: Run iOS Tests
        run: yarn test
