name: React Native CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    name: Build Android App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install
        working-directory: ./

      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
        working-directory: ./
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: android-app
          path: android/app/build/outputs/apk/release/app-release.apk

  deploy-to-play-store:
    name: Deploy to Play Store (Internal Track)
    runs-on: ubuntu-latest
    needs: build-android
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - name: Download APK
        uses: actions/download-artifact@v2
        with:
          name: android-app

      - name: Upload to Play Store (Internal Track)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT }}
          packageName: com.yourapppackagename # Replace with your app's package name
          releaseFiles: android-app/app-release.apk
          track: internal
          status: completed
          userFraction: 0.1 # Optional: Rollout to 10% of users
          whatsNewDirectory: ./whatsnew # Optional: Directory for release notes

